# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mexpro Mexico Insurance Professionals
email: mexico@mexpro.com
description: > # this means to ignore newlines until "baseurl:"
  Mexpro is the number one seller of Mexico auto insurance in the US. We have served over one-million customers with policies from top, A-rated companies with terrific claims records.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mexpro.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
google-analytics: UA-3065776-3
destination: "docs"
tme_quote_url: https://travelmedevac.com/quote/?orid=133&opid=66
tme_site_url: https://travelmedevac.com/?orid=133&opid=68

# Build settings
markdown: kramdown

# Plugins, yay!
plugins:
  # Creates an XML sitemap.
  #- jekyll-sitemap
  # Compile Coffeescript to Javascript.
  - jekyll-coffeescript
  # Compile all of the assets together.
  - jekyll-assets

assets:
  # Add a CDN for where to host static files.
  # cdn: "http://yourdomain.com"
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - LICENSE
  - README.md
  - server.sh
  - aliases

