branch-defaults:
  default:
    environment: feature-reverse-proxy
environment-defaults:
  feature-reverse-proxy:
    branch: null
    repository: null
global:
  application_name: Mexpro
  default_ec2_keyname: jack-2018
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Multi-container Docker
    running on 64bit Amazon Linux/2.8.4
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
